---
kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker:18
    settings:
      auto_tag: true
      dockerfile: Dockerfile
      repo: bibasoft/drone-s3
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
